export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_INFO = "GET_INFO";
export const GET_FORECAST = "GET_FORECAST";
export const WEATHER_LOADING = "WEATHER_LOADING";
export const GET_SETTINGS = "GET_SETTINGS";
export const SET_DRAWER_STATE = "SET_DRAWER_STATE";
